CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  booking_ref VARCHAR(128) NOT NULL,
  status ENUM('pending', 'confirmed', 'journey_completed', 'customer_billed', 'booking_completed', 'cancelled_by_customer', 'cancelled_by_us') NOT NULL DEFAULT 'pending',
  booking_date DATE NOT NULL,
  pickup_time TIME NOT NULL,
  estimated_return_time TIME NOT NULL,
  organisation VARCHAR(255) NOT NULL,
  destination_name VARCHAR(255) NOT NULL,
  destination_address VARCHAR(255) NULL,
  contact_name VARCHAR(255) NOT NULL,
  contact_email VARCHAR(255) NOT NULL,
  invoice_email VARCHAR(255) NOT NULL,
  contact_number VARCHAR(64) NOT NULL,
  static_wheelchairs TINYINT(1) NOT NULL DEFAULT 0,
  powered_wheelchairs TINYINT(1) NOT NULL DEFAULT 0,
  passenger_transfers TINYINT(1) NOT NULL DEFAULT 0,
  special_requirements TEXT NULL,
  start_mileage DECIMAL(8,2) NULL,
  finish_mileage DECIMAL(8,2) NULL,
  non_billable_mileage DECIMAL(8,2) NULL,
  checklist_lights_indicators ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_tyres ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_wheel_nuts ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_bodywork ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_mirrors_glass ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_brakes ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_steering ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_wipers_washers ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_dashboard_warning_lights ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_seats_seatbelts ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_emergency_equipment ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_wheelchair_lifts_restraints ENUM('ok', 'concern') NULL DEFAULT NULL,
  checklist_tail_lifts ENUM('ok', 'concern') NULL DEFAULT NULL,
  vehicle_check_date DATE NULL,
  vehicle_check_signed_by VARCHAR(255) NULL,
  vehicle_faults_recorded TEXT NULL,
  source_ip VARCHAR(45) NULL,
  user_agent VARCHAR(512) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bookings_booking_ref (booking_ref),
  KEY idx_bookings_booking_date (booking_date),
  KEY idx_bookings_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
